import math

# MAZE GENERATION - MAIN
MAZE_TYPE = 'complex' #simple or complex
MAZE_WIDTH = 35
MAZE_HEIGHT = 35
AGENT_AREA = ((0, 0), (2,2))
MIN_DISTANCE = 40
NUM_OF_TARGETS = 1
IS_SAVE = True # static or animation

# MONTE CARLO TREE SEARCH
MAX_ITERATIONS = 25000
EXPLORATION_CONSTANT = math.sqrt(2)
MAX_SIMULATION_ITERATIONS = 5000
MAX_SIMULATION_POINT = 5
BLOCKED_NODE_OUTCOME = -100
REDUCTION_FACTOR = 0.0001